package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class DollNameDomain extends BaseDomain {
    public static final String DOLL_GOODS_NAME = "dollGoodsName";
    public static final String DOLL_ORGANCODE = "dollOrgancode";
    public static final String DOLL_IMG_URL = "dollImgUrl";
    public static final String DOLL_COLOR = "dollColor";
    public static final String DOLL_TYPE = "dollType";
    public static final String DOLL_STATUS = "dollStatus";
    public static final String LOWER_PRICE = "lowerPrice";
    public static final String HEIGHER_PRICE = "heigherPrice";
    public static final String DESPRITON = "despriton";
}