package com.dollhouse.entity.comm;

import com.dollhouse.core.annotation.Table;
import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.entity.BaseEntity;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="admin_menu")
public class AdminMenu extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="pid")
    private Long pid;
    
    @Column(name="name")
    private String name;
    
    @Column(name="url")
    private String url;
    
    @Column(name="status")
    private String status;

    public Long getPid() {
        return pid;
    }
 
    public void setPid(Long pid) {
        this.pid = pid;
    }

    public String getName() {
        return name;
    }
 
    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }
 
    public void setUrl(String url) {
        this.url = url;
    }

    public String getStatus() {
        return status;
    }
 
    public void setStatus(String status) {
        this.status = status;
    }
}