package com.dollhouse.entity.comm;

import com.dollhouse.core.annotation.Table;
import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.entity.BaseEntity;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="chat_session")
public class ChatSession extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="user_session")
    private String userSession;

    public String getUserSession() {
        return userSession;
    }
 
    public void setUserSession(String userSession) {
        this.userSession = userSession;
    }
}