package com.dollhouse.entity.comm;

import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.annotation.Table;
import com.dollhouse.core.entity.BaseEntity;

/**
 * This code is generated by FreeMarker
 */
 @Table(name="ct_links")
public class CtLinks extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="category_id")
    private Integer categoryId;
    
    @Column(name="name")
    private String name;
    
    @Column(name="summary")
    private String summary;
    
    @Column(name="jumpurl")
    private String jumpurl;
    
    @Column(name="logo")
    private String logo;
    
    @Column(name="attachment_id")
    private Long attachmentId;
    
    @Column(name="add_time")
    private Long addTime;
    
    @Column(name="sort_index")
    private Integer sortIndex;
    
    @Column(name="status")
    private Integer status;

    public Integer getCategoryId() {
        return categoryId;
    }
 
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public String getName() {
        return name;
    }
 
    public void setName(String name) {
        this.name = name;
    }

    public String getSummary() {
        return summary;
    }
 
    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getJumpurl() {
        return jumpurl;
    }
 
    public void setJumpurl(String jumpurl) {
        this.jumpurl = jumpurl;
    }

    public String getLogo() {
        return logo;
    }
 
    public void setLogo(String logo) {
        this.logo = logo;
    }

    public Long getAttachmentId() {
        return attachmentId;
    }
 
    public void setAttachmentId(Long attachmentId) {
        this.attachmentId = attachmentId;
    }


    public Long getAddTime() {
		return addTime;
	}

	public void setAddTime(Long addTime) {
		this.addTime = addTime;
	}

	public Integer getSortIndex() {
        return sortIndex;
    }
 
    public void setSortIndex(Integer sortIndex) {
        this.sortIndex = sortIndex;
    }

    public Integer getStatus() {
        return status;
    }
 
    public void setStatus(Integer status) {
        this.status = status;
    }
}