package com.dollhouse.entity.comm;

import java.math.BigDecimal;
import com.dollhouse.core.annotation.Table;
import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.entity.BaseEntity;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="doll_order")
public class DollOrder extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="doll_name")
    private String dollName;
    
    @Column(name="doll_img")
    private String dollImg;
    
    @Column(name="doll_color")
    private String dollColor;
    
    @Column(name="doll_type")
    private String dollType;
    
    @Column(name="doll_price")
    private BigDecimal dollPrice;
    
    @Column(name="doll_num")
    private Long dollNum;
    
    @Column(name="doll_total")
    private BigDecimal dollTotal;
    
    @Column(name="login_user_id")
    private Long loginUserId;
    
    @Column(name="receive_name")
    private String receiveName;
    
    @Column(name="receive_phone")
    private String receivePhone;
    
    @Column(name="receive_address_province")
    private String receiveAddressProvince;
    
    @Column(name="receive_address_city")
    private String receiveAddressCity;
    
    @Column(name="receive_address_area")
    private String receiveAddressArea;
    
    @Column(name="receive_address_detial")
    private String receiveAddressDetial;
    
    @Column(name="leave_message")
    private String leaveMessage;
    
    @Column(name="buy_time")
    private String buyTime;
    
    @Column(name="handle_result")
    private Integer handleResult;

    public String getDollName() {
        return dollName;
    }
 
    public void setDollName(String dollName) {
        this.dollName = dollName;
    }

    public String getDollImg() {
        return dollImg;
    }
 
    public void setDollImg(String dollImg) {
        this.dollImg = dollImg;
    }

    public String getDollColor() {
        return dollColor;
    }
 
    public void setDollColor(String dollColor) {
        this.dollColor = dollColor;
    }

    public String getDollType() {
        return dollType;
    }
 
    public void setDollType(String dollType) {
        this.dollType = dollType;
    }

    public BigDecimal getDollPrice() {
        return dollPrice;
    }
 
    public void setDollPrice(BigDecimal dollPrice) {
        this.dollPrice = dollPrice;
    }

    public Long getDollNum() {
        return dollNum;
    }
 
    public void setDollNum(Long dollNum) {
        this.dollNum = dollNum;
    }

    public BigDecimal getDollTotal() {
        return dollTotal;
    }
 
    public void setDollTotal(BigDecimal dollTotal) {
        this.dollTotal = dollTotal;
    }

    public Long getLoginUserId() {
        return loginUserId;
    }
 
    public void setLoginUserId(Long loginUserId) {
        this.loginUserId = loginUserId;
    }

    public String getReceiveName() {
        return receiveName;
    }
 
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName;
    }

    public String getReceivePhone() {
        return receivePhone;
    }
 
    public void setReceivePhone(String receivePhone) {
        this.receivePhone = receivePhone;
    }

    public String getReceiveAddressProvince() {
        return receiveAddressProvince;
    }
 
    public void setReceiveAddressProvince(String receiveAddressProvince) {
        this.receiveAddressProvince = receiveAddressProvince;
    }

    public String getReceiveAddressCity() {
        return receiveAddressCity;
    }
 
    public void setReceiveAddressCity(String receiveAddressCity) {
        this.receiveAddressCity = receiveAddressCity;
    }

    public String getReceiveAddressArea() {
        return receiveAddressArea;
    }
 
    public void setReceiveAddressArea(String receiveAddressArea) {
        this.receiveAddressArea = receiveAddressArea;
    }

    public String getReceiveAddressDetial() {
        return receiveAddressDetial;
    }
 
    public void setReceiveAddressDetial(String receiveAddressDetial) {
        this.receiveAddressDetial = receiveAddressDetial;
    }

    public String getLeaveMessage() {
        return leaveMessage;
    }
 
    public void setLeaveMessage(String leaveMessage) {
        this.leaveMessage = leaveMessage;
    }

    public String getBuyTime() {
        return buyTime;
    }
 
    public void setBuyTime(String buyTime) {
        this.buyTime = buyTime;
    }

    public Integer getHandleResult() {
        return handleResult;
    }
 
    public void setHandleResult(Integer handleResult) {
        this.handleResult = handleResult;
    }
}