package com.dollhouse.entity.comm;

import java.math.BigDecimal;
import com.dollhouse.core.annotation.Table;
import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.entity.BaseEntity;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="doll_menu")
public class DollMenu extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="pid")
    private Long pid;
    
    @Column(name="name")
    private String name;
    
    @Column(name="link_id")
    private Long linkId;
    
    @Column(name="menu_price")
    private BigDecimal menuPrice;
    
    @Column(name="menu_type")
    private String menuType;
    
    @Column(name="menu_img_url")
    private String menuImgUrl;
    
    @Column(name="menu_status")
    private String menuStatus;
    
    @Column(name="menu_location")
    private String menuLocation;
    
    @Column(name="menu_label")
    private String menuLabel;

    public Long getPid() {
        return pid;
    }
 
    public void setPid(Long pid) {
        this.pid = pid;
    }

    public String getName() {
        return name;
    }
 
    public void setName(String name) {
        this.name = name;
    }

    public Long getLinkId() {
        return linkId;
    }
 
    public void setLinkId(Long linkId) {
        this.linkId = linkId;
    }

    public BigDecimal getMenuPrice() {
        return menuPrice;
    }
 
    public void setMenuPrice(BigDecimal menuPrice) {
        this.menuPrice = menuPrice;
    }

    public String getMenuType() {
        return menuType;
    }
 
    public void setMenuType(String menuType) {
        this.menuType = menuType;
    }

    public String getMenuImgUrl() {
        return menuImgUrl;
    }
 
    public void setMenuImgUrl(String menuImgUrl) {
        this.menuImgUrl = menuImgUrl;
    }

    public String getMenuStatus() {
        return menuStatus;
    }
 
    public void setMenuStatus(String menuStatus) {
        this.menuStatus = menuStatus;
    }

    public String getMenuLocation() {
        return menuLocation;
    }
 
    public void setMenuLocation(String menuLocation) {
        this.menuLocation = menuLocation;
    }

    public String getMenuLabel() {
        return menuLabel;
    }
 
    public void setMenuLabel(String menuLabel) {
        this.menuLabel = menuLabel;
    }
}