package com.dollhouse.entity.comm;

import java.math.BigDecimal;
import com.dollhouse.core.annotation.Table;
import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.entity.BaseEntity;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="doll_star")
public class DollStar extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="doll_name")
    private String dollName;
    
    @Column(name="doll_organcode")
    private String dollOrgancode;
    
    @Column(name="doll_imgUrl")
    private String dollImgurl;
    
    @Column(name="doll_lowerPrice")
    private BigDecimal dollLowerprice;
    
    @Column(name="add_time")
    private String addTime;

    public String getDollName() {
        return dollName;
    }
 
    public void setDollName(String dollName) {
        this.dollName = dollName;
    }

    public String getDollOrgancode() {
        return dollOrgancode;
    }
 
    public void setDollOrgancode(String dollOrgancode) {
        this.dollOrgancode = dollOrgancode;
    }

    public String getDollImgurl() {
        return dollImgurl;
    }
 
    public void setDollImgurl(String dollImgurl) {
        this.dollImgurl = dollImgurl;
    }

    public BigDecimal getDollLowerprice() {
        return dollLowerprice;
    }
 
    public void setDollLowerprice(BigDecimal dollLowerprice) {
        this.dollLowerprice = dollLowerprice;
    }

    public String getAddTime() {
        return addTime;
    }
 
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }
}