package com.dollhouse.entity.comm;

import java.math.BigDecimal;
import com.dollhouse.core.annotation.Table;
import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.entity.BaseEntity;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="doll_shop_car")
public class DollShopCar extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="user_id")
    private Long userId;
    
    @Column(name="doll_name")
    private String dollName;
    
    @Column(name="doll_img")
    private String dollImg;
    
    @Column(name="doll_organcode")
    private String dollOrgancode;
    
    @Column(name="doll_color")
    private String dollColor;
    
    @Column(name="doll_type")
    private String dollType;
    
    @Column(name="doll_price")
    private BigDecimal dollPrice;
    
    @Column(name="doll_num")
    private Long dollNum;
    
    @Column(name="doll_total")
    private BigDecimal dollTotal;

    public Long getUserId() {
        return userId;
    }
 
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getDollName() {
        return dollName;
    }
 
    public void setDollName(String dollName) {
        this.dollName = dollName;
    }

    public String getDollImg() {
        return dollImg;
    }
 
    public void setDollImg(String dollImg) {
        this.dollImg = dollImg;
    }

    public String getDollOrgancode() {
        return dollOrgancode;
    }
 
    public void setDollOrgancode(String dollOrgancode) {
        this.dollOrgancode = dollOrgancode;
    }

    public String getDollColor() {
        return dollColor;
    }
 
    public void setDollColor(String dollColor) {
        this.dollColor = dollColor;
    }

    public String getDollType() {
        return dollType;
    }
 
    public void setDollType(String dollType) {
        this.dollType = dollType;
    }

    public BigDecimal getDollPrice() {
        return dollPrice;
    }
 
    public void setDollPrice(BigDecimal dollPrice) {
        this.dollPrice = dollPrice;
    }

    public Long getDollNum() {
        return dollNum;
    }
 
    public void setDollNum(Long dollNum) {
        this.dollNum = dollNum;
    }

    public BigDecimal getDollTotal() {
        return dollTotal;
    }
 
    public void setDollTotal(BigDecimal dollTotal) {
        this.dollTotal = dollTotal;
    }
}