package com.dollhouse.entity.comm;

import java.util.Date;

import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.annotation.Table;
import com.dollhouse.core.entity.BaseEntity;

 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="mb_member")
public class MbMember extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="name")
    private String name;
    
    @Column(name="password")
    private String password;
    
    @Column(name="email")
    private String email;
    
    @Column(name="phone")
    private Long phone;
    
    @Column(name="paypassword")
    private String paypassword;
    
    @Column(name="count")
    private Integer count;
    
    @Column(name="register_ip")
    private Long registerIp;
    
    @Column(name="register_time")
    private Long registerTime;
    
    @Column(name="register_date")
    private Date registerDate;
    
    @Column(name="lastlogin_ip")
    private Long lastloginIp;
    
    @Column(name="lastlogin_time")
    private Long lastloginTime;
    
    @Column(name="lastlogin_date")
    private Date lastloginDate;
    
    @Column(name="register_type")
    private Integer registerType;
    
    @Column(name="is_realname")
    private Integer isRealname;
    
    @Column(name="is_email")
    private Integer isEmail;
    
    @Column(name="is_phone")
    private Integer isPhone;
    
    @Column(name="pwd_attach")
    private String pwdAttach;
    
    @Column(name="status")
    private Integer status;
    
    @Column(name="lock_time")
    private Long lockTime;

    public String getName() {
        return name;
    }
 
    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }
 
    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }
 
    public void setEmail(String email) {
        this.email = email;
    }

    public Long getPhone() {
        return phone;
    }
 
    public void setPhone(Long phone) {
        this.phone = phone;
    }

    public String getPaypassword() {
        return paypassword;
    }
 
    public void setPaypassword(String paypassword) {
        this.paypassword = paypassword;
    }

    public Integer getCount() {
        return count;
    }
 
    public void setCount(Integer count) {
        this.count = count;
    }

    public Long getRegisterIp() {
        return registerIp;
    }
 
    public void setRegisterIp(Long registerIp) {
        this.registerIp = registerIp;
    }

    public Long getRegisterTime() {
        return registerTime;
    }
 
    public void setRegisterTime(Long registerTime) {
        this.registerTime = registerTime;
    }

    public Date getRegisterDate() {
        return registerDate;
    }
 
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    public Long getLastloginIp() {
        return lastloginIp;
    }
 
    public void setLastloginIp(Long lastloginIp) {
        this.lastloginIp = lastloginIp;
    }

    public Long getLastloginTime() {
        return lastloginTime;
    }
 
    public void setLastloginTime(Long lastloginTime) {
        this.lastloginTime = lastloginTime;
    }

    public Date getLastloginDate() {
        return lastloginDate;
    }
 
    public void setLastloginDate(Date lastloginDate) {
        this.lastloginDate = lastloginDate;
    }

    public Integer getRegisterType() {
        return registerType;
    }
 
    public void setRegisterType(Integer registerType) {
        this.registerType = registerType;
    }

    public Integer getIsRealname() {
        return isRealname;
    }
 
    public void setIsRealname(Integer isRealname) {
        this.isRealname = isRealname;
    }

    public Integer getIsEmail() {
        return isEmail;
    }
 
    public void setIsEmail(Integer isEmail) {
        this.isEmail = isEmail;
    }

    public Integer getIsPhone() {
        return isPhone;
    }
 
    public void setIsPhone(Integer isPhone) {
        this.isPhone = isPhone;
    }

    public String getPwdAttach() {
        return pwdAttach;
    }
 
    public void setPwdAttach(String pwdAttach) {
        this.pwdAttach = pwdAttach;
    }

    public Integer getStatus() {
        return status;
    }
 
    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getLockTime() {
        return lockTime;
    }
 
    public void setLockTime(Long lockTime) {
        this.lockTime = lockTime;
    }
}