package com.dollhouse.entity.comm;

import java.util.Date;
import com.dollhouse.core.annotation.Table;
import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.entity.BaseEntity;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="sale_statistics")
public class SaleStatistics extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="sale_type_name")
    private String saleTypeName;
    
    @Column(name="sale_type_num")
    private Long saleTypeNum;
    
    @Column(name="sale_num_time")
    private Date saleNumTime;

    public String getSaleTypeName() {
        return saleTypeName;
    }
 
    public void setSaleTypeName(String saleTypeName) {
        this.saleTypeName = saleTypeName;
    }

    public Long getSaleTypeNum() {
        return saleTypeNum;
    }
 
    public void setSaleTypeNum(Long saleTypeNum) {
        this.saleTypeNum = saleTypeNum;
    }

    public Date getSaleNumTime() {
        return saleNumTime;
    }
 
    public void setSaleNumTime(Date saleNumTime) {
        this.saleNumTime = saleNumTime;
    }
}