package com.dollhouse.entity.comm;

import java.util.Date;
import com.dollhouse.core.annotation.Table;
import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.entity.BaseEntity;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="user_info")
public class UserInfo extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="user_name")
    private String userName;
    
    @Column(name="user_password")
    private String userPassword;
    
    @Column(name="user_email")
    private String userEmail;
    
    @Column(name="user_phone")
    private String userPhone;
    
    @Column(name="user_identification")
    private String userIdentification;
    
    @Column(name="user_register_time")
    private Date userRegisterTime;

    public String getUserName() {
        return userName;
    }
 
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserPassword() {
        return userPassword;
    }
 
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public String getUserEmail() {
        return userEmail;
    }
 
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getUserPhone() {
        return userPhone;
    }
 
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    public String getUserIdentification() {
        return userIdentification;
    }
 
    public void setUserIdentification(String userIdentification) {
        this.userIdentification = userIdentification;
    }

    public Date getUserRegisterTime() {
        return userRegisterTime;
    }
 
    public void setUserRegisterTime(Date userRegisterTime) {
        this.userRegisterTime = userRegisterTime;
    }
}