package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class DollShopCarDomain extends BaseDomain {
    public static final String USER_ID = "userId";
    public static final String DOLL_NAME = "dollName";
    public static final String DOLL_IMG = "dollImg";
    public static final String DOLL_ORGANCODE = "dollOrgancode";
    public static final String DOLL_COLOR = "dollColor";
    public static final String DOLL_TYPE = "dollType";
    public static final String DOLL_PRICE = "dollPrice";
    public static final String DOLL_NUM = "dollNum";
    public static final String DOLL_TOTAL = "dollTotal";
}