package com.dollhouse.core.entity;

import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.annotation.Table;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="mb_system_sms_log")
public class MbSystemSmsLog extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="member_id")
    private Long memberId;
    
    @Column(name="member_name")
    private String memberName;
    
    @Column(name="type")
    private Integer type;
    
    @Column(name="phone")
    private Long phone;
    
    @Column(name="contents")
    private String contents;
    
    @Column(name="return_data")
    private String returnData;
    
    @Column(name="send_url")
    private String sendUrl;
    
    @Column(name="add_time")
    private Long addTime;
    
    @Column(name="send_time")
    private Long sendTime;
    
    @Column(name="return_time")
    private Long returnTime;
    
    @Column(name="status")
    private Integer status;
    
    @Column(name="sms_port_id")
    private Integer smsPortId;

    public Long getMemberId() {
        return memberId;
    }
 
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    public String getMemberName() {
        return memberName;
    }
 
    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    public Integer getType() {
        return type;
    }
 
    public void setType(Integer type) {
        this.type = type;
    }

    public Long getPhone() {
        return phone;
    }
 
    public void setPhone(Long phone) {
        this.phone = phone;
    }

    public String getContents() {
        return contents;
    }
 
    public void setContents(String contents) {
        this.contents = contents;
    }

    public String getReturnData() {
        return returnData;
    }
 
    public void setReturnData(String returnData) {
        this.returnData = returnData;
    }

    public String getSendUrl() {
        return sendUrl;
    }
 
    public void setSendUrl(String sendUrl) {
        this.sendUrl = sendUrl;
    }


    public Long getAddTime() {
		return addTime;
	}

	public void setAddTime(Long addTime) {
		this.addTime = addTime;
	}

	public Long getSendTime() {
		return sendTime;
	}

	public void setSendTime(Long sendTime) {
		this.sendTime = sendTime;
	}

	public Long getReturnTime() {
		return returnTime;
	}

	public void setReturnTime(Long returnTime) {
		this.returnTime = returnTime;
	}

	public Integer getStatus() {
        return status;
    }
 
    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getSmsPortId() {
        return smsPortId;
    }
 
    public void setSmsPortId(Integer smsPortId) {
        this.smsPortId = smsPortId;
    }
}