package com.dollhouse.core.entity;

import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.annotation.Table;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="mb_system_email_log")
public class MbSystemEmailLog extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="member_id")
    private Long memberId;
    
    @Column(name="member_name")
    private String memberName;
    
    @Column(name="type")
    private Integer type;
    
    @Column(name="title")
    private String title;
    
    @Column(name="contents")
    private String contents;
    
    @Column(name="send_email")
    private String sendEmail;
    
    @Column(name="member_email")
    private String memberEmail;
    
    @Column(name="send_type")
    private Integer sendType;
    
    @Column(name="add_time")
    private Long addTime;
    
    @Column(name="send_time")
    private Long sendTime;
    
    @Column(name="status")
    private Integer status;

    public Long getMemberId() {
        return memberId;
    }
 
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    public String getMemberName() {
        return memberName;
    }
 
    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    public Integer getType() {
        return type;
    }
 
    public void setType(Integer type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }
 
    public void setTitle(String title) {
        this.title = title;
    }

    public String getContents() {
        return contents;
    }
 
    public void setContents(String contents) {
        this.contents = contents;
    }

    public String getSendEmail() {
        return sendEmail;
    }
 
    public void setSendEmail(String sendEmail) {
        this.sendEmail = sendEmail;
    }

    public String getMemberEmail() {
        return memberEmail;
    }
 
    public void setMemberEmail(String memberEmail) {
        this.memberEmail = memberEmail;
    }

    public Integer getSendType() {
        return sendType;
    }
 
    public void setSendType(Integer sendType) {
        this.sendType = sendType;
    }


    public Long getAddTime() {
		return addTime;
	}

	public void setAddTime(Long addTime) {
		this.addTime = addTime;
	}

	public Long getSendTime() {
		return sendTime;
	}

	public void setSendTime(Long sendTime) {
		this.sendTime = sendTime;
	}

	public Integer getStatus() {
        return status;
    }
 
    public void setStatus(Integer status) {
        this.status = status;
    }
}