package com.dollhouse.core.entity;

import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.annotation.Table;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="sys_email_port")
public class SysEmailPort extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="email_smtp")
    private String emailSmtp;
    
    @Column(name="email_port")
    private Integer emailPort;
    
    @Column(name="email_account")
    private String emailAccount;
    
    @Column(name="email_password")
    private String emailPassword;
    
    @Column(name="email_nickname")
    private String emailNickname;
    
    @Column(name="add_time")
    private Long addTime;
    
    @Column(name="upd_time")
    private Long updTime;
    
    @Column(name="sort_index")
    private Integer sortIndex;
    
    @Column(name="title")
    private String title;
    
    @Column(name="status")
    private Integer status;

    public String getEmailSmtp() {
        return emailSmtp;
    }
 
    public void setEmailSmtp(String emailSmtp) {
        this.emailSmtp = emailSmtp;
    }


    public Integer getEmailPort() {
		return emailPort;
	}

	public void setEmailPort(Integer emailPort) {
		this.emailPort = emailPort;
	}

	public String getEmailAccount() {
        return emailAccount;
    }
 
    public void setEmailAccount(String emailAccount) {
        this.emailAccount = emailAccount;
    }

    public String getEmailPassword() {
        return emailPassword;
    }
 
    public void setEmailPassword(String emailPassword) {
        this.emailPassword = emailPassword;
    }

    public String getEmailNickname() {
        return emailNickname;
    }
 
    public void setEmailNickname(String emailNickname) {
        this.emailNickname = emailNickname;
    }

    public Long getAddTime() {
        return addTime;
    }
 
    public void setAddTime(Long addTime) {
        this.addTime = addTime;
    }

    public Long getUpdTime() {
        return updTime;
    }
 
    public void setUpdTime(Long updTime) {
        this.updTime = updTime;
    }

    public Integer getSortIndex() {
        return sortIndex;
    }
 
    public void setSortIndex(Integer sortIndex) {
        this.sortIndex = sortIndex;
    }

    public String getTitle() {
        return title;
    }
 
    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getStatus() {
        return status;
    }
 
    public void setStatus(Integer status) {
        this.status = status;
    }
}