package com.dollhouse.core.entity;

import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.annotation.Table;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="sys_email_template")
public class SysEmailTemplate extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="type")
    private Integer type;
    
    @Column(name="title")
    private String title;
    
    @Column(name="contents")
    private String contents;
    
    @Column(name="status")
    private Integer status;

    public Integer getType() {
        return type;
    }
 
    public void setType(Integer type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }
 
    public void setTitle(String title) {
        this.title = title;
    }

    public String getContents() {
        return contents;
    }
 
    public void setContents(String contents) {
        this.contents = contents;
    }

    public Integer getStatus() {
        return status;
    }
 
    public void setStatus(Integer status) {
        this.status = status;
    }
}