package com.dollhouse.core.entity;

import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.annotation.Table;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="sys_system_sms_port")
public class SysSystemSmsPort extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="name")
    private String name;
    
    @Column(name="port_server")
    private String portServer;
    
    @Column(name="account")
    private String account;
    
    @Column(name="password")
    private String password;
    
    @Column(name="send_url")
    private String sendUrl;
    
    @Column(name="sign_name")
    private String signName;
    
    @Column(name="remark")
    private String remark;
    
    @Column(name="status")
    private Integer status;
    
    @Column(name="count")
    private Long count;
    
    @Column(name="sort_index")
    private Integer sortIndex;

    public String getName() {
        return name;
    }
 
    public void setName(String name) {
        this.name = name;
    }

    public String getPortServer() {
        return portServer;
    }
 
    public void setPortServer(String portServer) {
        this.portServer = portServer;
    }

    public String getAccount() {
        return account;
    }
 
    public void setAccount(String account) {
        this.account = account;
    }

    public String getPassword() {
        return password;
    }
 
    public void setPassword(String password) {
        this.password = password;
    }

    public String getSendUrl() {
        return sendUrl;
    }
 
    public void setSendUrl(String sendUrl) {
        this.sendUrl = sendUrl;
    }

    public String getSignName() {
        return signName;
    }
 
    public void setSignName(String signName) {
        this.signName = signName;
    }

    public String getRemark() {
        return remark;
    }
 
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getStatus() {
        return status;
    }
 
    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getCount() {
        return count;
    }
 
    public void setCount(Long count) {
        this.count = count;
    }

    public Integer getSortIndex() {
        return sortIndex;
    }
 
    public void setSortIndex(Integer sortIndex) {
        this.sortIndex = sortIndex;
    }
}