package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class DollTypeDomain extends BaseDomain {
    public static final String TYPE_ID = "typeId";
    public static final String DOLL_NAME_ID = "dollNameId";
    public static final String DOLL_TYPE_NAME = "dollTypeName";
    public static final String DOLL_TYPE_PRICE = "dollTypePrice";
    public static final String DOLL_TYPE_NUM = "dollTypeNum";
}