package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class AdminMenuDomain extends BaseDomain {
    public static final String PID = "pid";
    public static final String NAME = "name";
    public static final String URL = "url";
    public static final String STATUS = "status";
}