package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class AdminInfoDomain extends BaseDomain {
    public static final String ADMIN_NAME = "adminName";
    public static final String ADMIN_ICON = "adminIcon";
    public static final String ADMIN_PASSWORD = "adminPassword";
    public static final String ADMIN_EMAIL = "adminEmail";
    public static final String ADMIN_PHONE = "adminPhone";
    public static final String ADMIN_IDENTIFICATION = "adminIdentification";
    public static final String ADMIN_ADD_TIME = "adminAddTime";
    public static final String ADMIN_GRADE = "adminGrade";
    public static final String STATUS = "status";
}