package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class AdminMenuLevelDomain extends BaseDomain {
    public static final String NAME = "name";
    public static final String ADMIN_LEVEL = "adminLevel";
    public static final String STATUS = "status";
}