package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class ChatSessionDomain extends BaseDomain {
    public static final String USER_SESSION = "userSession";
}