package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class CtLinksDomain extends BaseDomain {
    public static final String CATEGORY_ID = "categoryId";
    public static final String NAME = "name";
    public static final String SUMMARY = "summary";
    public static final String JUMPURL = "jumpurl";
    public static final String LOGO = "logo";
    public static final String ATTACHMENT_ID = "attachmentId";
    public static final String ADD_TIME = "addTime";
    public static final String SORT_INDEX = "sortIndex";
    public static final String STATUS = "status";
}