package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class DollStarDomain extends BaseDomain {
    public static final String DOLL_NAME = "dollName";
    public static final String DOLL_ORGANCODE = "dollOrgancode";
    public static final String DOLL_IMGURL = "dollImgurl";
    public static final String DOLL_LOWERPRICE = "dollLowerprice";
    public static final String ADD_TIME = "addTime";
}