package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class DollMenuDomain extends BaseDomain {
    public static final String PID = "pid";
    public static final String NAME = "name";
    public static final String LINK_ID = "linkId";
    public static final String MENU_PRICE = "menuPrice";
    public static final String MENU_TYPE = "menuType";
    public static final String MENU_IMG_URL = "menuImgUrl";
    public static final String MENU_STATUS = "menuStatus";
    public static final String MENU_LOCATION = "menuLocation";
    public static final String MENU_LABEL = "menuLabel";
}