package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class MbMemberInfoDomain extends BaseDomain {
    public static final String MEMBER_ID = "memberId";
    public static final String MEMBER_NAME = "memberName";
    public static final String AVATAR = "avatar";
    public static final String NICKNAME = "nickname";
    public static final String REALNAME = "realname";
    public static final String GENDER = "gender";
    public static final String BIRTHDAY = "birthday";
    public static final String CARD_ID = "cardId";
    public static final String QQ = "qq";
    public static final String EDUCATIONAL_BACKGROUND = "educationalBackground";
    public static final String MARRY_STATUS = "marryStatus";
    public static final String GRADUATED = "graduated";
    public static final String COMPANY_INDUSTRY = "companyIndustry";
    public static final String COMPANY_SCALE = "companyScale";
    public static final String COMPANY_OFFICE = "companyOffice";
    public static final String MONTHLY_INCOME = "monthlyIncome";
    public static final String INVITE_MONEY = "inviteMoney";
    public static final String HOMETOWN_PROVINCE = "hometownProvince";
    public static final String HOMETOWN_CITY = "hometownCity";
    public static final String HOMETOWN_AREA = "hometownArea";
    public static final String HOMETOWN_POST = "hometownPost";
}