package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class MbMemberDomain extends BaseDomain {
    public static final String NAME = "name";
    public static final String PASSWORD = "password";
    public static final String EMAIL = "email";
    public static final String PHONE = "phone";
    public static final String PAYPASSWORD = "paypassword";
    public static final String COUNT = "count";
    public static final String REGISTER_IP = "registerIp";
    public static final String REGISTER_TIME = "registerTime";
    public static final String REGISTER_DATE = "registerDate";
    public static final String LASTLOGIN_IP = "lastloginIp";
    public static final String LASTLOGIN_TIME = "lastloginTime";
    public static final String LASTLOGIN_DATE = "lastloginDate";
    public static final String REGISTER_TYPE = "registerType";
    public static final String IS_REALNAME = "isRealname";
    public static final String IS_EMAIL = "isEmail";
    public static final String IS_PHONE = "isPhone";
    public static final String PWD_ATTACH = "pwdAttach";
    public static final String STATUS = "status";
    public static final String LOCK_TIME = "lockTime";
}