package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class SysSystemConfigDomain extends BaseDomain {
    public static final String NAME = "name";
    public static final String NID = "nid";
    public static final String VALUE = "value";
    public static final String REMARK = "remark";
    public static final String STATUS = "status";
}