package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class UserInfoDomain extends BaseDomain {
    public static final String USER_NAME = "userName";
    public static final String USER_PASSWORD = "userPassword";
    public static final String USER_EMAIL = "userEmail";
    public static final String USER_PHONE = "userPhone";
    public static final String USER_IDENTIFICATION = "userIdentification";
    public static final String USER_REGISTER_TIME = "userRegisterTime";
}