package com.dollhouse.entity.comm;

import com.dollhouse.core.annotation.Table;
import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.entity.BaseEntity;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="sys_system_config")
public class SysSystemConfig extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="name")
    private String name;
    
    @Column(name="nid")
    private String nid;
    
    @Column(name="value")
    private String value;
    
    @Column(name="remark")
    private String remark;
    
    @Column(name="status")
    private Integer status;

    public String getName() {
        return name;
    }
 
    public void setName(String name) {
        this.name = name;
    }

    public String getNid() {
        return nid;
    }
 
    public void setNid(String nid) {
        this.nid = nid;
    }

    public String getValue() {
        return value;
    }
 
    public void setValue(String value) {
        this.value = value;
    }

    public String getRemark() {
        return remark;
    }
 
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getStatus() {
        return status;
    }
 
    public void setStatus(Integer status) {
        this.status = status;
    }
}