package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class MoneyStatisticsDomain extends BaseDomain {
    public static final String MONEY_STATISTICS_TIME = "moneyStatisticsTime";
    public static final String MONEY_STATISTICS_TYPE = "moneyStatisticsType";
    public static final String MONEY_STATISTICS_DAYTOTAL = "moneyStatisticsDaytotal";
}