package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class SaleStatisticsDomain extends BaseDomain {
    public static final String SALE_TYPE_NAME = "saleTypeName";
    public static final String SALE_TYPE_NUM = "saleTypeNum";
    public static final String SALE_NUM_TIME = "saleNumTime";
}