package com.dollhouse.entity.comm.domain;

import com.dollhouse.core.entity.domain.BaseDomain;

/**
 * This code is generated by FreeMarker
 */
public class DollOrderDomain extends BaseDomain {
    public static final String DOLL_NAME = "dollName";
    public static final String DOLL_IMG = "dollImg";
    public static final String DOLL_COLOR = "dollColor";
    public static final String DOLL_TYPE = "dollType";
    public static final String DOLL_PRICE = "dollPrice";
    public static final String DOLL_NUM = "dollNum";
    public static final String DOLL_TOTAL = "dollTotal";
    public static final String LOGIN_USER_ID = "loginUserId";
    public static final String RECEIVE_NAME = "receiveName";
    public static final String RECEIVE_PHONE = "receivePhone";
    public static final String RECEIVE_ADDRESS_PROVINCE = "receiveAddressProvince";
    public static final String RECEIVE_ADDRESS_CITY = "receiveAddressCity";
    public static final String RECEIVE_ADDRESS_AREA = "receiveAddressArea";
    public static final String RECEIVE_ADDRESS_DETIAL = "receiveAddressDetial";
    public static final String LEAVE_MESSAGE = "leaveMessage";
    public static final String BUY_TIME = "buyTime";
    public static final String HANDLE_RESULT = "handleResult";
}