package com.dollhouse.entity.comm;

import java.math.BigDecimal;
import com.dollhouse.core.annotation.Table;
import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.entity.BaseEntity;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="money_statistics")
public class MoneyStatistics extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="money_statistics_time")
    private String moneyStatisticsTime;
    
    @Column(name="money_statistics_type")
    private String moneyStatisticsType;
    
    @Column(name="money_statistics_dayTotal")
    private BigDecimal moneyStatisticsDaytotal;

    public String getMoneyStatisticsTime() {
        return moneyStatisticsTime;
    }
 
    public void setMoneyStatisticsTime(String moneyStatisticsTime) {
        this.moneyStatisticsTime = moneyStatisticsTime;
    }

    public String getMoneyStatisticsType() {
        return moneyStatisticsType;
    }
 
    public void setMoneyStatisticsType(String moneyStatisticsType) {
        this.moneyStatisticsType = moneyStatisticsType;
    }

    public BigDecimal getMoneyStatisticsDaytotal() {
        return moneyStatisticsDaytotal;
    }
 
    public void setMoneyStatisticsDaytotal(BigDecimal moneyStatisticsDaytotal) {
        this.moneyStatisticsDaytotal = moneyStatisticsDaytotal;
    }
}