package com.dollhouse.entity.comm;

import com.dollhouse.core.annotation.Table;
import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.entity.BaseEntity;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="admin_info")
public class AdminInfo extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="admin_name")
    private String adminName;
    
    @Column(name="admin_icon")
    private String adminIcon;
    
    @Column(name="admin_password")
    private String adminPassword;
    
    @Column(name="admin_email")
    private String adminEmail;
    
    @Column(name="admin_phone")
    private String adminPhone;
    
    @Column(name="admin_identification")
    private String adminIdentification;
    
    @Column(name="admin_add_time")
    private Long adminAddTime;
    
    @Column(name="admin_grade")
    private Long adminGrade;
    
    @Column(name="status")
    private Long status;

    public String getAdminName() {
        return adminName;
    }
 
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    public String getAdminIcon() {
        return adminIcon;
    }
 
    public void setAdminIcon(String adminIcon) {
        this.adminIcon = adminIcon;
    }

    public String getAdminPassword() {
        return adminPassword;
    }
 
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }

    public String getAdminEmail() {
        return adminEmail;
    }
 
    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }

    public String getAdminPhone() {
        return adminPhone;
    }
 
    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone;
    }

    public String getAdminIdentification() {
        return adminIdentification;
    }
 
    public void setAdminIdentification(String adminIdentification) {
        this.adminIdentification = adminIdentification;
    }

    public Long getAdminAddTime() {
        return adminAddTime;
    }
 
    public void setAdminAddTime(Long adminAddTime) {
        this.adminAddTime = adminAddTime;
    }

    public Long getAdminGrade() {
        return adminGrade;
    }
 
    public void setAdminGrade(Long adminGrade) {
        this.adminGrade = adminGrade;
    }

    public Long getStatus() {
        return status;
    }
 
    public void setStatus(Long status) {
        this.status = status;
    }
}