package com.dollhouse.core.entity;

import com.dollhouse.core.annotation.Column;
import com.dollhouse.core.annotation.Table;
 
/**
 * This code is generated by FreeMarker
 */
 @Table(name="sys_system_sms_template")
public class SysSystemSmsTemplate extends BaseEntity {
    private static final long serialVersionUID = 1L;
    
    @Column(name="name")
    private String name;
    
    @Column(name="nid")
    private String nid;
    
    @Column(name="content")
    private String content;
    
    @Column(name="add_time")
    private Integer addTime;
    
    @Column(name="add_admin_id")
    private Integer addAdminId;
    
    @Column(name="update_time")
    private Integer updateTime;
    
    @Column(name="update_admin_id")
    private Integer updateAdminId;
    
    @Column(name="status")
    private Integer status;

    public String getName() {
        return name;
    }
 
    public void setName(String name) {
        this.name = name;
    }

    public String getNid() {
        return nid;
    }
 
    public void setNid(String nid) {
        this.nid = nid;
    }

    public String getContent() {
        return content;
    }
 
    public void setContent(String content) {
        this.content = content;
    }

    public Integer getAddTime() {
        return addTime;
    }
 
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    public Integer getAddAdminId() {
        return addAdminId;
    }
 
    public void setAddAdminId(Integer addAdminId) {
        this.addAdminId = addAdminId;
    }

    public Integer getUpdateTime() {
        return updateTime;
    }
 
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getUpdateAdminId() {
        return updateAdminId;
    }
 
    public void setUpdateAdminId(Integer updateAdminId) {
        this.updateAdminId = updateAdminId;
    }

    public Integer getStatus() {
        return status;
    }
 
    public void setStatus(Integer status) {
        this.status = status;
    }
}